
---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.order.eline.add
  name:  Mapper Of Creating Order Connection
  description: This operation creates a ProductOrder entity
  version: 3
spec:
  trigger:
    path: /mefApi/sonata/productOrderingManagement/v10/productOrder
    method: post
    productType: access_e_line
    actionType: add
  endpoints:
    - id: create connection order
      path: ""
      method: ""
      serverKey: ""
      mappers:
        request:
          - name: mapper.order.uni.add.buyerId
            title: "The unique identifier of the organization that is acting as the a Buyer."
            description: ""
            source: "@{{buyerId}}"
            sourceLocation: "QUERY"
            target: ""
            targetLocation: ""
            requiredMapping: false
        response:
          - name: mapper.order.eline.add.state
            title: "Order State"
            description: ""
            target: "@{{state}}"
            targetType: enum
            targetLocation: BODY
            requiredMapping: true
            targetValues:
              - acknowledged
              - assessingCancellation
              - held.assessingCharge
              - pending.assessingModification
              - cancelled
              - pendingCancellation
              - completed
              - failed
              - inProgress
              - partial
              - rejected
            valueMapping: {}
            source: ""
            sourceLocation: ""
          - name: mapper.order.eline.add.orderId
            title: "order Id from seller"
            description: orderId mapping
            source: ""
            sourceLocation: ""
            target: "@{{orderId}}"
            targetLocation: BODY
            requiredMapping: true
          - name: mapper.order.eline.add.instanceId
            title: "instance id from seller"
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{instanceId}}"
            targetLocation: "BODY"
            requiredMapping: false
