---
kind: kraken.component.api-target-mapper
apiVersion: v1
metadata:
  key: mef.sonata.api-target-mapper.order.uni.read
  name: Mapper Of Reading Order Port
  description: This operation retrieves a ProductOrder entity
  version: 3
spec:
  trigger:
    path: /mefApi/sonata/productOrderingManagement/v10/productOrder/{id}
    method: get
    productType: uni
  endpoints:
    - id: retrieve connection detail by id
      path: ""
      method: ""
      serverKey: ""
      mappers:
        request:
          - name: mapper.order.uni.read.buyerId
            title: "The unique identifier of the organization that is acting as the a Buyer."
            description: ""
            source: "@{{buyerId}}"
            sourceLocation: "QUERY"
            target: ""
            targetLocation: ""
            requiredMapping: false
        response:
          - name: mapper.order.uni.read.state
            title: "ProductOrderState"
            description: ""
            target: "@{{state}}"
            targetType: enum
            targetLocation: BODY
            requiredMapping: true
            targetValues:
              - acknowledged
              - assessingCancellation
              - held.assessingCharge
              - pending.assessingModification
              - cancelled
              - pendingCancellation
              - completed
              - failed
              - inProgress
              - partial
              - rejected
            valueMapping: {}
            source: ""
            sourceLocation: ""
          - name: mapper.order.uni.read.instanceId
            title: "instance id from seller"
            description: ""
            source: ""
            sourceLocation: ""
            target: "@{{instanceId}}"
            targetLocation: "BODY"
            requiredMapping: false
