---
kind: kraken.component.api-target
apiVersion: v1
metadata:
  key: mef.sonata.api-target.order.uni.read
  mapperKey: mef.sonata.api-target-mapper.order.uni.read
  name: Order Connection API
  version: 8
spec:
  inputs:
    - mefQuery
    - mefRequestBody
    - entity
  trigger:
    path: /mefApi/sonata/productOrderingManagement/v10/productOrder/{id}
    method: get
    productType: uni
  endpoints:
    - id: retrieve connection detail by id
      path: ""
      method: ""
      pathReferId: "mef.sonata.api-target-mapper.order.uni.add#mapper.order.uni.add.orderId"
      responseBody: |
        { 
          "id": "${entity.id}",
          "relatedContactInformation": "${T(com.consoleconnect.kraken.operator.gateway.func.SpelFunc).appendSellerInformation(env.seller.role, env.seller.name, env.seller.emailAddress, env.seller.number, entity.request.relatedContactInformation)}",
          "productOrderItem": "${entity.request.productOrderItem}",
          "state": "@{{state}}",
          "orderDate":"${entity.renderedResponse.orderDate}",
          "orderId": "${entity.renderedResponse.orderId}",
          "instanceId": "@{{instanceId}}"
        }