---
kind: kraken.product.mapping.matrix
apiVersion: v1
metadata:
  key: mef.sonata.api.matrix.order
  name: MEF Sonata API
  labels:
    mef-api-release: grace
  version: 11
spec:
  matrix:
    mef.sonata.api-target.order.uni.add:
      - name: product_type_UNI
        path: "$.body.productOrderItem[*].product.productConfiguration.['@type']"
        expected: UNI
      - name: action_add
        path: "$.body.productOrderItem[*].['action']"
        expected: add
    mef.sonata.api-target.order.eline.add:
      - name: product_type_eline
        path: "$.body.productOrderItem[*].product.productConfiguration.['@type']"
        expected: ACCESS_E_LINE
      - name: action_add
        path: "$.body.productOrderItem[*].['action']"
        expected: add
    mef.sonata.api-target.order.eline.delete:
      - name: product_type_eline
        path: "$.body.productOrderItem[*].product.productConfiguration.['@type']"
        expected: ACCESS_E_LINE
      - name: action_delete
        path: "$.body.productOrderItem[*].['action']"
        expected: delete
    mef.sonata.api-target.order.uni.delete:
      - name: product_type_uni
        path: "$.body.productOrderItem[*].product.productConfiguration.['@type']"
        expected: UNI
      - name: action_delete
        path: "$.body.productOrderItem[*].['action']"
        expected: delete

