---
kind: kraken.product.mapping.matrix
apiVersion: v1
metadata:
  key: mef.sonata.api.matrix.address.validation
  name: MEF Sonata API
  labels:
    mef-api-release: grace
  version: 10
spec:
  matrix:
    mef.sonata.api-target.address.validate:
      - name: provide_alternative_true
        path: "$.body.provideAlternative"
        expected: true
      - name: address_type_FieldedAddress
        path: "$.body.submittedGeographicAddress.['@type']"
        expected: FieldedAddress


