---
kind: kraken.product.mapping.matrix
apiVersion: v1
metadata:
  key: mef.sonata.api.matrix.address.validation
  name: MEF Sonata API
  labels:
    mef-api-release: grace
  version: 10
spec:
  matrix:
    mef.sonata.api-target.address.validate:
      - name: provide_alternative_true
        path: "$.body.provideAlternative"
        expected: true
      - name: address_type_FieldedAddress
        path: "$.body.submittedGeographicAddress.['@type']"
        expected: FieldedAddress
      - name: address_submittedGeographicAddress_country
        path: "$.body.submittedGeographicAddress.['country']"
        expectedTrue: "${param!=''}"
        errorMsg: "submittedGeographicAddress.country can not be null"
      - name: address_submittedGeographicAddress_city
        path: "$.body.submittedGeographicAddress.['city']"
        expectedTrue: "${param!=''}"
        errorMsg: "submittedGeographicAddress.city can not be null"
      - name: address_submittedGeographicAddress_streetName
        path: "$.body.submittedGeographicAddress.['streetName']"
        expectedTrue: "${param!=''}"
        errorMsg: "submittedGeographicAddress.streetName can not be null"



