---
kind: kraken.product.template-upgrade
apiVersion: v1
metadata:
  key: kraken.product.template-upgrade.1.3.0
  name: V1.3
  labels:
    release-version: V1.3
    release-date: 2024-09-11
  description: |
    New feature:
      Add functions related to demo environment
    

  version: 1

